### ISSUE TITLE
"Transfer failed" on a lot of archives

### ISSUE THREAD

**Issue by nderjung** [mandatoryprogrammer/TLDR#3]
I was interested in looking at different archives to see what was available but everything I've looked at doesn't contain any information, just "Transfer failed" where I suspect a list of TLD information should be.

**Comment by mandatoryprogrammer** [comment]
Hey @escproxy have you checked out https://github.com/mandatoryprogrammer/TLDR/blob/master/transferable_zones.md ? That has a list of all the TLDs which currently allow zone transfers.
